import type { Trip } from "@/store/types";

export const seedTrips: Trip[] = [
  {
    id: "trip-001",
    title: "Bangkok Market Expansion Q2",
    country: "Thailand",
    cities: ["Bangkok", "Chiang Mai"],
    assignee: "Andre Wijaya",
    startDate: "2026-05-20",
    endDate: "2026-05-25",
    status: "in_progress",
    marketIntel: { importDuty: "30%", vat: "7%", certifications: "FDA Thailand, Halal" },
    competitors: [
      {
        id: "c1", brand: "MAMA", flavour: "Tom Yum", noodleType: "Wavy thin",
        price: "฿6 / pack", presence: "Dominant nationwide",
        caption: "End-cap dominance at Tesco Lotus — biggest direct rival.",
        photo: { id: "cp1", url: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=900",
                 caption: "MAMA end-cap, Sukhumvit branch" },
      },
      {
        id: "c2", brand: "Wai Wai", flavour: "Pork", noodleType: "Crispy thick",
        price: "฿5 / pack", presence: "Strong rural",
        caption: "Cheaper alternative; strong outside Bangkok.",
      },
    ],
    appointments: [
      { id: "a1", partner: "Big C Distribution", date: "2026-05-21", status: "confirmed",
        location: "Big C HQ, Bangkok", contact: "Khun Pim (Category Buyer)",
        agenda: "Introduce premium noodle line, discuss listing fees",
        outcome: "Verbal interest, awaiting price matrix",
        notes: "Bring spicy & tom yum samples; prefers 4pk format" },
      { id: "a2", partner: "7-Eleven Buying Office", date: "2026-05-22", status: "confirmed",
        location: "CP Tower, Silom", contact: "Mr. Somchai",
        agenda: "Convenience SKU pitch", outcome: "Requested 90-day exclusivity",
        notes: "Strict on packaging dimensions" },
    ],
    toolkit: { items: [
      { id: "t1", label: "Compliance-ready product samples", checked: true, notes: "24 packs across 6 SKUs" },
      { id: "t2", label: "Localized brochures (digital/physical)", checked: true, notes: "Thai + English" },
      { id: "t3", label: "Price list matrix (FOB, CIF, DDP)", checked: true, notes: "Updated 2026-05-10" },
      { id: "t4", label: "Legal/contract templates for new leads", checked: false, notes: "Awaiting legal" },
    ]},
    retailAudits: [{
      id: "r1", storeName: "Tesco Lotus Sukhumvit", lat: 13.7367, lng: 100.5602,
      shelfPrice: "฿8.5", promoPrice: "฿7.0",
      category: "Hypermarket", contactPerson: "Store Manager — K. Nan",
      notes: "End-cap display dominated by MAMA. Our category at eye-level shelf 3.",
      details: [
        { id: "d1", label: "Facings", value: "12 (vs MAMA 28)" },
        { id: "d2", label: "Out of stock SKUs", value: "Spicy beef" },
        { id: "d3", label: "Promo mechanic", value: "Buy 5 get 1 free" },
      ],
      photos: [
        { id: "p1", url: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=900", caption: "Aisle wide-shot, 5pm peak" },
        { id: "p2", url: "https://images.unsplash.com/photo-1617196039897-3a1d6d9aa1a6?w=900", caption: "Shelf 3 — our category placement" },
        { id: "p3", url: "https://images.unsplash.com/photo-1567337710282-00832b415979?w=900", caption: "MAMA promo end-cap" },
      ],
    }],
    partnerLogs: [{
      id: "pl1", partner: "Big C", notes: "Interested in spicy variant",
      painPoint: "Slow customs clearance", evidence: "Showed last shipment delay log (14 days vs 7 SLA).",
      photos: [{ id: "pp1", url: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=900",
                 caption: "Meeting with Big C category team" }],
    }],
    sentiment: [{
      id: "s1", note: "Consumers prefer thicker noodles", competitor: "MAMA",
      photos: [{ id: "sp1", url: "https://images.unsplash.com/photo-1612392061787-2d078b3e573f?w=900",
                 caption: "Shopper interview at Tops Market" }],
    }],
    postVisitPhotos: [
      { id: "pv1", url: "https://images.unsplash.com/photo-1526318472351-c75fcf070305?w=900",
        caption: "Team debrief at hotel — day 3" },
    ],
    moments: [
      {
        id: "m1", createdAt: "2026-05-21T10:15:00.000Z", day: "2026-05-21",
        kind: "observation", title: "MAMA end-cap dominates entry aisle",
        note: "Walked into Tesco Lotus Sukhumvit — MAMA owns the first 6m of shelving with a Buy 5 Get 1 mechanic.",
        location: "Tesco Lotus Sukhumvit",
        photos: [], includeInReport: true,
      },
    ],
    report: { followUpSent: false, forecastVolume: 25000, adjustments: "Reduce salt by 10%, add Thai label" },
  },
  {
    id: "trip-002",
    title: "Manila Distributor Sweep",
    country: "Philippines",
    cities: ["Manila"],
    assignee: "Siti Rahma",
    startDate: "2026-04-10",
    endDate: "2026-04-15",
    status: "completed",
    marketIntel: { importDuty: "10%", vat: "12%", certifications: "FDA Philippines" },
    competitors: [{
      id: "c1", brand: "Lucky Me!", flavour: "Pancit Canton", noodleType: "Stir-fry dry",
      price: "₱9 / pack", presence: "Market leader",
      caption: "Owns ~70% share — must differentiate on flavour, not price.",
    }],
    appointments: [{
      id: "a1", partner: "SM Supermarket", date: "2026-04-11", status: "confirmed",
      location: "SM Megamall, Mandaluyong", contact: "Ms. Liza Reyes",
      agenda: "Annual review + new SKU listing", outcome: "Approved 3 new SKUs",
      notes: "Wants Q3 promo plan by May",
    }],
    toolkit: { items: [
      { id: "t1", label: "Compliance-ready product samples", checked: true, notes: "" },
      { id: "t2", label: "Localized brochures (digital/physical)", checked: true, notes: "Tagalog version" },
      { id: "t3", label: "Price list matrix (FOB, CIF, DDP)", checked: true, notes: "" },
      { id: "t4", label: "Legal/contract templates for new leads", checked: true, notes: "Signed with SM" },
    ]},
    retailAudits: [{
      id: "r2", storeName: "SM Hypermarket Makati", lat: 14.5547, lng: 121.0244,
      shelfPrice: "₱12", promoPrice: "₱10",
      category: "Hypermarket", contactPerson: "K. Reyes",
      notes: "Strong shelf share, premium positioning works.",
      details: [],
      photos: [
        { id: "p1", url: "https://images.unsplash.com/photo-1612392061787-2d078b3e573f?w=900", caption: "Premium aisle, eye-level" },
        { id: "p2", url: "https://images.unsplash.com/photo-1626804475297-41608ea09aeb?w=900", caption: "Store frontage" },
      ],
    }],
    partnerLogs: [],
    sentiment: [],
    postVisitPhotos: [],
    moments: [],
    report: { followUpSent: true, forecastVolume: 18000, adjustments: "Sweeter broth profile" },
  },
  {
    id: "trip-003",
    title: "Tokyo Premium Channel",
    country: "Japan",
    cities: ["Tokyo"],
    assignee: "Reza Pratama",
    startDate: "2026-06-05",
    endDate: "2026-06-10",
    status: "planned",
    isDraft: true,
    marketIntel: { importDuty: "21.3%", vat: "10%", certifications: "JAS, Japan Food Sanitation Act" },
    competitors: [{
      id: "c1", brand: "Nissin", flavour: "Shoyu", noodleType: "Cup ramen",
      price: "¥120 / pack", presence: "Dominant",
      caption: "Category creator — beat them on premium positioning, not on price.",
    }],
    appointments: [],
    toolkit: { items: [
      { id: "t1", label: "Compliance-ready product samples", checked: false, notes: "" },
      { id: "t2", label: "Localized brochures (digital/physical)", checked: false, notes: "" },
      { id: "t3", label: "Price list matrix (FOB, CIF, DDP)", checked: false, notes: "" },
      { id: "t4", label: "Legal/contract templates for new leads", checked: false, notes: "" },
    ]},
    retailAudits: [],
    partnerLogs: [],
    sentiment: [],
    postVisitPhotos: [],
    moments: [],
    report: { followUpSent: false, forecastVolume: 0, adjustments: "" },
  },
];
